#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|bugfix|improvement|library|prerelease|release|hotfix)\/[a-z0-9._-]+$"

message="\n\n There is something wrong with your branch name. Branch names in this project must adhere to this contract:\n\n $valid_branch_regex. \n\n Please rename your branch to a valid name and try again. \n\n\n To rename your branch please run: \n git branch -m <your-new-branch-name> \n\n\n"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

npm jest

exit 0
